### PR TITLE
fix: add self-connection guard in should_accept()

### LINKED ISSUE #2139: Bug: Node can accept self-connection due to missing guard in connect protocol
## Problem

When a joiner connects to a gateway that has no other peers, the connect request can be forwarded back to the joiner, causing the node to accept a connection from **itself** and attempt NAT traversal to its own public IP.

## User Impact

- "Subscribing to room..." hangs indefinitely in River
- Node fails to properly join the network when the gateway has limited peers
- Connection attempts timeout with "max connection attempts reached" trying to connect to self

## Root Cause

Two missing guards in the connect protocol:

1. **`should_accept()` in `connection_manager.rs:149`** - doesn't check if `peer_id == self.get_peer_key()`
2. **Gateway forwarding logic** - the gateway forwards the ConnectRequest back to the only peer it knows (the joiner)

### Reproduction Log Evidence

```
# Joiner receives ConnectRequest with itself as joiner:
ConnectRequest { target: v6MWKgqHiBMNcGtG, ttl: 9, joiner: v6MWKgqHkAt4vEzk }

# Joiner accepts connection from itself:
acceptance issued, acceptor_peer: v6MWKgqHkAt4vEzk, joiner_peer: v6MWKgqHkAt4vEzk

# Then tries to connect to its own public IP:
Connecting to peer, tx: ..., remote_addr: 136.62.52.28:43375

# Which fails:
Outbound handshake failed: max connection attempts reached
```

## Proposed Fix

Add a self-connection guard in `should_accept()`:

```rust
pub fn should_accept(&self, location: Location, peer_id: &PeerId) -> bool {
    // Don't accept connections from ourselves
    if let Some(own_id) = self.get_peer_key() {
        if &own_id == peer_id {
            tracing::warn!(%peer_id, "should_accept: rejecting self-connection attempt");
            return false;
        }
    }
    // ... rest of method
}
```

This should be a simple fix.

## Environment
- Freenet v0.1.38
- River (commit recent)

## Additional Context

Note: there's already a `debug_assert!` at `connection_manager.rs:400` checking this condition in `add_connection()`, suggesting this case was considered but not fully guarded against:
```rust
debug_assert!(self.get_peer_key().expect("should be set") != peer);
```

[AI-assisted - Claude]

### PR DESCRIPTION
**Pull request by sanity**
## Problem

When a joiner connects to a gateway that has no other peers, the connect request can be forwarded back to the joiner itself. Without a guard, the joiner would accept this connection to itself, causing a self-connection.

This scenario occurs during early network bootstrap when:
1. Joiner connects to gateway
2. Gateway has no other peers to forward to
3. Gateway forwards connect request back to joiner
4. Joiner evaluates `should_accept()` for its own connection request

## Solution

Add an early guard in `should_accept()` that checks if the incoming peer ID matches the node's own peer ID. If they match, the connection is rejected immediately with a warning log.

```rust
// Don't accept connections from ourselves
if let Some(own_id) = self.get_peer_key() {
    if &own_id == peer_id {
        tracing::warn!(%peer_id, "should_accept: rejecting self-connection attempt");
        return false;
    }
}
```

## Testing

Added two unit tests:
- `rejects_self_connection` - verifies that `should_accept()` returns `false` when the peer ID matches the node's own ID
- `accepts_connection_from_different_peer` - verifies normal connections from other peers are still accepted

## Fixes

Closes #2139

[AI-assisted - Claude]

### CODE REVIEW

**Comment by sanity** [comment]
@claude Please review this PR and the original issue #2139 it fixes. Verify the fix is correct and complete.

File: crates/core/src/ring/connection_manager.rs [hunk 1]
```diff
@@ -147,6 +147,14 @@ impl ConnectionManager {
     /// # Panic
     /// Will panic if the node checking for this condition has no location assigned.
     pub fn should_accept(&self, location: Location, peer_id: &PeerId) -> bool {
+        // Don't accept connections from ourselves
```
Comment (iduartgomez) [inline crates/core/src/ring/connection_manager.rs:150]: this fix is ok, but the main issue is that we are not adding self to the skip_list of connect so it wont be a possible target at all in the gateway, we should look into that
