### PR TITLE
fix: wire up proximity cache state exchange on connection establishment

### LINKED ISSUE #2718: fix: Proximity cache doesn't exchange state on peer connection (dead code)
## Problem

When two peers connect, they should exchange information about which contracts they're caching so they can share updates. The code for this exists but is **never called** - it's dead code with `#[allow(dead_code)]`.

This means connected peers caching the same contract don't know about each other and can't share updates through the proximity mechanism.

## Evidence

Contract `3iuVXozkJr...` had 5 different states across peers. The proximity cache should have synchronized them, but peers didn't know their neighbors had the contract.

## Root Cause

In `crates/core/src/node/proximity_cache.rs`:

```rust
// Line 267-271
/// Generate a cache state request for a newly connected peer.
#[allow(dead_code)]  // ← Compiler knew it was unused!
pub fn request_cache_state() -> ProximityCacheMessage {
    ProximityCacheMessage::CacheStateRequest
}
```

The response handler at lines 197-213 EXISTS and works correctly:
- Receives `CacheStateRequest`
- Returns `CacheStateResponse` with all cached contract keys
- Caller processes response and updates neighbor contract lists

But `request_cache_state()` is never called when a new peer connects.

## Solution

1. Find where new peer connections are established (likely `peer_connection.rs` or connection handling in `transport/`)
2. Call `request_cache_state()` when a peer successfully connects
3. Send the resulting `ProximityCacheMessage::CacheStateRequest` to the new peer
4. The existing response handler will do the rest

## Files to Examine

- `crates/core/src/node/proximity_cache.rs` - Main file, contains the dead code
  - Lines 267-271: `request_cache_state()` - the dead code to wire up
  - Lines 197-213: Handler for request/response - already works
  - Lines 232-254: `neighbors_with_contract()` - uses the data once populated
- `crates/core/src/transport/peer_connection.rs` - Peer connection lifecycle
- `crates/core/src/operations/update.rs:659-678` - Uses proximity neighbors for broadcasts

## Testing

1. Set up two peers caching the same contract
2. Verify they exchange `CacheStateRequest`/`CacheStateResponse` on connect
3. Verify `neighbors_with_contract()` returns the peer after exchange
4. Verify updates propagate through proximity cache path

## Related

Part of #2717 (contract state divergence umbrella)

[AI-assisted - Claude]

### PR DESCRIPTION
**Pull request by sanity**
## Problem

The proximity cache feature exists to enable UPDATE forwarding to nearby peers who cache contracts but may not be explicitly subscribed. However, the `request_cache_state()` function was never called - it had `#[allow(dead_code)]` annotation.

This meant:
1. When peers connect, they never exchange their cached contract lists
2. `neighbor_caches` in `ProximityCacheManager` stays empty
3. `neighbors_with_contract()` always returns empty, so UPDATE forwarding to nearby seeders never happens

The response handler for `CacheStateResponse` existed and worked correctly, but the request was never sent.

## This Solution

Wire up `request_cache_state()` to be called when connections are established and promoted to ring:

1. After a connection is established and promoted to ring (in `handle_successful_connection`)
2. Send `CacheStateRequest` to the new peer
3. Peer responds with `CacheStateResponse` containing their cached contracts
4. We update `neighbor_caches` with this information

The request is sent right after `InterestSync`, following the same pattern for early connection setup messages.

Key points:
- Only ring-promoted connections trigger the request (transient connections excluded)
- Error handling logs warnings if request fails
- Uses the existing `request_cache_state()` function which was already implemented but unused

## Testing

- All 13 proximity_cache unit tests pass
- Tests verify message handling, bidirectional awareness, and ping-pong termination
- Clippy passes with no warnings

## Verification in Production

To verify this works in production, check logs for:
- `"Sent CacheStateRequest to new peer"` - confirms requests are being sent
- `"Received full cache state from neighbor"` - confirms responses are processed
- `"Found neighbors with contract"` - confirms cache state is being used

Fixes #2718

[AI-assisted - Claude]

### CODE REVIEW

File: crates/core/src/node/network_bridge/p2p_protoc.rs [hunk 1]
```diff
@@ -2857,6 +2857,25 @@ impl P2pConnManager {
                     }
                 }
 
+                // Send CacheStateRequest to exchange proximity cache state with new peer.
```
Comment (iduartgomez) [inline crates/core/src/node/network_bridge/p2p_protoc.rs]: why is this op-specific logic leaking into p2p_protoc which should be naive about message contents? this should be handled within the op itself.

**Review by iduartgomez — CHANGES_REQUESTED** [review]
@claude leaking op details into abstract network messaging  layer, leading to spaghettification

**Comment by sanity** [comment]
Addressed the review feedback by refactoring to use a lifecycle hook pattern.

**Changes:**
1. Added `on_ring_connection_established()` method to `ProximityCacheManager` (follows the same pattern as `on_peer_disconnected()`)
2. Updated `p2p_protoc.rs` to call the lifecycle hook instead of directly constructing messages
3. Removed the `ProximityCacheManager` import from p2p_protoc.rs

Now the "when to send cache state request" logic is encapsulated within `ProximityCacheManager` rather than in the abstract networking layer. The p2p_protoc just calls the lifecycle hook and sends whatever message (if any) it returns.

[AI-assisted - Claude]

**Comment by sanity** [comment]
## Subagent Review Summary

Ran four parallel reviews as per PR creation skill guidelines:

### 1. Code-First Review ✅
- Core functionality is sound
- Minor: Log messages in PR description are stale (updated in refactor)

### 2. Testing Review ✅
- Test coverage is **adequate** - 13 existing unit tests cover message handling
- Existing `connectivity.rs` and `six-peer-regression` CI tests exercise the integration path
- No blocking test gaps identified

### 3. Skeptical Review ✅ (Low Risk)
- **Bidirectional message storm**: Both peers send `CacheStateRequest` on connection (4 messages instead of 2). Inefficient but correct - could optimize in future PR
- **No race conditions**: Ring promotion happens before sending request
- **Error handling adequate**: Send failures logged as warnings, don't crash connection

### 4. Big Picture Review ✅
- Correctly solves the stated problem (#2718)
- No anti-patterns detected (no ignored tests, weakened assertions, CI-chasing)
- Part of coordinated effort for #2717 umbrella issue

### Action Taken
- Removed redundant `request_cache_state()` function (flagged by all reviews as dead code after refactor)

### Deferred Items (Future PRs)
- Optimize to avoid bidirectional request storm (one side could skip requesting)
- Add explicit integration test for the wiring point

[AI-assisted - Claude]

**Comment by sanity** [comment]
**Note on CI failure:** The `test_select3_determinism` test failure is unrelated to this PR's changes. It's a pre-existing flaky test in `deterministic_select.rs` that checks RNG determinism. The test passed on the previous CI run (run 21065680827) and on main branch.

Re-running CI to verify.

[AI-assisted - Claude]
