### PR TITLE
fix: address pre-existing cache store issues (#3487)

### LINKED ISSUE #3487: fix: address pre-existing cache store issues found during moka migration review
## Context

During review of the stretto → moka cache migration (7732aeafc5d85a07eace6c6e2bfc16eb839ea824), several pre-existing issues were identified that were not introduced by the migration but are worth addressing.

### 1. Cache-before-persist ordering incoherence
`StateStore::store()` and `update()` insert to cache before persisting to disk. If the persist operation fails, the cache holds stale/incorrect data that will be served on subsequent reads.

**Fix:** Insert to cache only after successful persist, or invalidate on persist failure.

### 2. `remove_contract()` doesn't invalidate cache
After removing a contract from persistent storage, cached entries remain and could serve "ghost" contracts.

**Fix:** Call `cache.invalidate()` / `cache.remove()` in `remove_contract()`.

### 3. `max_size` is `i64` but used as `u64`
`max_size as u64` from `i64` — a negative `i64` would wrap to `u64::MAX`. Inherited from stretto's API convention.

**Fix:** Change the type to `u64` or add a bounds check.

### 4. Weigher `as u32` truncation
All 3 weighers cast `.len()` to `u32`. Safe today (MAX_STATE_SIZE=50 MiB, WASM modules are small), but moka recommends `.try_into().unwrap_or(u32::MAX)` as a defensive pattern.

### 5. `DelegateCode` not `Arc`-wrapped in `DelegateStore`
Moka clones values on `get()`. `ContractStore` wraps in `Arc<ContractCode>` (cheap clone) but `DelegateStore` stores `DelegateCode<'static>` directly, causing full clones on cache hits.

**Fix:** Wrap in `Arc<DelegateCode<'static>>` for cheap clones, matching the `ContractStore` pattern.

## Files involved
- `crates/core/src/contract/storages/state.rs`
- `crates/core/src/contract/storages/contract.rs`
- `crates/core/src/contract/storages/delegate.rs`

### PR DESCRIPTION
**Pull request by netsirius**
## Problem

During the stretto → moka cache migration review, several pre-existing correctness issues were identified in the contract/delegate/state storage layer:

1. **Cache-before-persist ordering** — `StateStore::store()` and `update()` inserted to cache before persisting to disk. If persist failed, the cache held data that was never saved, serving "phantom" state on subsequent reads.
2. **Ghost contracts after removal** — `ContractStore::remove_contract()` deleted from disk and index but never invalidated the cache, allowing removed contracts to be served from memory.
3. **`max_size` signed/unsigned mismatch** — `ContractStore::new()` and `DelegateStore::new()` accepted `i64` and cast to `u64`. A negative value from misconfiguration would wrap to `u64::MAX`, making the cache effectively unbounded.
4. **Weigher `u32` truncation** — All three weighers cast `.len()` to `u32` via `as`, which silently truncates values above 4 GiB to 0, making moka believe a huge entry weighs nothing and never evicting it.
5. **`DelegateCode` not `Arc`-wrapped** — Moka clones values on `get()`. `ContractStore` already wraps in `Arc<ContractCode>` (cheap clone) but `DelegateStore` stored `DelegateCode<'static>` directly, causing full WASM module clones on every cache hit.

## Solution

- **Issue 1**: Reorder `StateStore::store()` and `update()` to persist first, then cache. This follows the write-through pattern already used by `ContractStore::store_contract()`.
- **Issue 2**: Add `contract_cache.invalidate()` in `remove_contract()`, matching the pattern already used by `DelegateStore::remove_delegate()`.
- **Issue 3**: Change `max_size` parameter from `i64` to `u64` in both `ContractStore::new()` and `DelegateStore::new()`, eliminating the unsafe cast entirely.
- **Issue 4**: Replace `as u32` with `.try_into().unwrap_or(u32::MAX)` in all three weighers, following moka's recommended defensive pattern.
- **Issue 5**: Change `DelegateStore` cache from `MokaCache<CodeHash, DelegateCode<'static>>` to `MokaCache<CodeHash, Arc<DelegateCode<'static>>>`, matching the `ContractStore` pattern.

## Testing

- **`test_cached_store_failure_does_not_leave_stale_cache`** — Verifies that after a failed `store()`, the cache does not serve the unpersisted data.
- **`test_cached_update_failure_preserves_original_state`** — Verifies that after a failed `update()`, the cache still serves the last successfully persisted state.
- **`test_remove_contract_invalidates_cache`** — Verifies that after `remove_contract()`, `fetch_contract()` returns `None` (no ghost contracts from cache).
- All existing storage tests continue to pass.

## Fixes

Closes #3487

### CODE REVIEW

File: crates/core/src/wasm_runtime/delegate_store.rs [hunk 1]
```diff
@@ -117,10 +117,12 @@ impl DelegateStore {
...
         Ok(Self {
             delegate_cache: MokaCache::builder()
-                .max_capacity(max_size as u64)
-                .weigher(|_key: &CodeHash, value: &DelegateCode<'static>| -> u32 {
-                    value.as_ref().len() as u32
-                })
+                .max_capacity(max_size)
+                .weigher(
+                    |_key: &CodeHash, value: &Arc<DelegateCode<'static>>| -> u32 {
+                        value.as_ref().as_ref().len().try_into().unwrap_or(u32::MAX)
```
Comment (iduartgomez) [inline crates/core/src/wasm_runtime/delegate_store.rs]: add a warning in case the conversion fails here, definitively this shouldn't happen and will be a bug (we should be controllign this elsewhere, bot that we are right now

File: crates/core/src/wasm_runtime/state_store.rs [hunk 2]
```diff
@@ -93,7 +93,9 @@ where
     pub fn new(store: S, max_size: u32) -> Result<Self, StateStoreError> {
         let cache = MokaCache::builder()
             .max_capacity(max_size as u64)
-            .weigher(|_key: &ContractKey, value: &WrappedState| -> u32 { value.size() as u32 })
+            .weigher(|_key: &ContractKey, value: &WrappedState| -> u32 {
+                value.size().try_into().unwrap_or(u32::MAX)
```
Comment (iduartgomez) [inline crates/core/src/wasm_runtime/state_store.rs]: same as above

**Comment by iduartgomez** [comment]
## Comprehensive PR Review

### Summary
- **Type:** fix (5 distinct correctness fixes bundled)
- **CI Status:** All passing (Clippy, Fmt, Unit&Integration, Simulation, NAT, Windows)
- **Size:** +145 / -28 across 4 source files

---

### Code-First Analysis

**Independent understanding of the diff:**
1. `state_store.rs` — `store()` and `update()` reordered: persist-then-cache, plus weigher uses `try_into().unwrap_or(u32::MAX)`.
2. `contract_store.rs` — `remove_contract()` calls `contract_cache.invalidate()`; `max_size: i64 → u64`; weigher uses `try_into`.
3. `delegate_store.rs` — `max_size: i64 → u64`; weigher uses `try_into`; cache value type `DelegateCode<'static>` → `Arc<DelegateCode<'static>>`.
4. `executor.rs` — call site updated: `MAX_SIZE: i64 → u64`.

**Alignment:** Fully matches stated intent. Each of the five enumerated issues is addressed with a minimal, targeted change. No scope creep.

---

### Testing Assessment

**Coverage Level:** Adequate for the surfaced bugs.

**New regression tests:**
1. `test_cached_store_failure_does_not_leave_stale_cache` — verifies failed `store()` doesn't pollute cache (issue 1).
2. `test_cached_update_failure_preserves_original_state` — verifies failed `update()` preserves prior state (issue 1).
3. `test_remove_contract_invalidates_cache` — verifies removed contract isn't served from cache (issue 2).

**Coverage gaps (not blocking):**
- Issues 3 (signed→unsigned), 4 (`u32` truncation), 5 (`Arc` wrap) have no dedicated tests. These are compile-time / defense-in-depth / perf fixes where runtime tests would be hard to construct meaningfully.
- No test for the partial-failure path in `store()` where `store_params` fails after `store` succeeds — see Skeptical Findings.

The 3 added tests use the existing `MockStateStorage::fail_next_stores(1)` helper, already battle-tested elsewhere in the file.

---

### Skeptical Findings

**Risk Level:** Low

| # | Concern | Severity | Details |
|---|---------|----------|---------|
| 1 | Partial-success window in `store()` | Low | New ordering: `store()` → `store_params()` → cache. If `store_params` fails after `store` succeeds, disk has state without params, and cache has neither. **Strictly better** than pre-fix behavior, but worth documenting. |
| 2 | `Arc::new(...)` allocation on every cache insert in `delegate_store.rs` | Low | Trade-off shifts allocation cost from many `get`s to each `insert`. Right call (gets >> inserts). |
| 3 | `try_into().unwrap_or(u32::MAX)` saturation | Low | Unreachable in practice given `MAX_STATE_SIZE = 50 MiB`. Defense-in-depth as moka docs recommend. |
| 4 | `remove_contract` invalidate ordering | None | `invalidate()` before disk removal. If disk removal fails, next fetch repopulates from disk — correct (cache is a derivable view). |

**Recurring bug pattern checklist:** This PR is exactly the "state cleanup on failure" pattern — addressed correctly. Other patterns N/A.

---

### Big Picture Assessment

- **Goal Alignment:** Yes — directly addresses all 5 issues enumerated in #3487.
- **Anti-patterns detected:** None. No removed tests, no weakened assertions, no `#[ignore]`, no error swallowing.
- **Scope:** Focused. Bundling 5 small storage-layer fixes is justified — they share context (moka migration review), share files, and individually would create review overhead.
- **Architecture:** The persist-before-cache pattern matches `ContractStore::store_contract()`'s existing behavior, restoring consistency across the storage layer.

---

### Recommendations

**Must Fix (Blocking):** None.

**Should Fix (Important):**
1. Add a brief comment in `store()` noting the partial-failure window: if `store_params` fails after `store` succeeds, the on-disk state will be orphaned (no params) and the cache will not be populated. Either accept and document, or wrap both in a transaction/cleanup. A one-line comment is sufficient given pre-fix behavior was worse.

**Consider (Suggestions):**
1. Defense-in-depth comment on weighers explaining `try_into().unwrap_or(u32::MAX)` is moka's recommended pattern, since `MAX_STATE_SIZE = 50 MiB` makes overflow unreachable.
2. Follow-up issue for the orphaned-state-on-`store_params`-failure scenario — likely needs a transaction or cleanup pass, out of scope here.

---

### Verdict

**Ready to Merge: Yes** (Should-Fix is optional, not blocking)

High-quality, tightly-scoped PR that fixes 5 real correctness issues in the storage layer with minimal risk:
- All fixes match the documented issue descriptions exactly
- Three regression tests cover the two most impactful behavioral fixes
- No anti-patterns; no removed tests; no scope creep
- All CI checks pass including Windows, Simulation, and NAT validation
- Code is consistent with existing patterns in the codebase

The single residual concern (partial-failure window in `store()`/`store_params()`) is a pre-existing class of issue made *less bad* by this PR, not introduced by it.

File: crates/core/src/wasm_runtime/delegate_store.rs (hunk 1 above)
Comment (iduartgomez) [reply crates/core/src/wasm_runtime/delegate_store.rs]: Done in 3f7ee555 — added a tracing::warn! that fires if the conversion ever overflows, with a note that hitting it indicates a bug elsewhere (since MAX_STATE_SIZE / module size limits should make it unreachable). Applied the same pattern consistently to the contract_store and state_store weighers.

File: crates/core/src/wasm_runtime/state_store.rs (hunk 2 above)
Comment (iduartgomez) [reply crates/core/src/wasm_runtime/state_store.rs]: Done in 3f7ee555 — same pattern as delegate_store: tracing::warn! with a note that this should be impossible given MAX_STATE_SIZE=50 MiB enforcement upstream, so a hit means the upstream check is broken.
