### PR TITLE
fix: prevent message loss in peer_connection_listener race condition

### LINKED ISSUE #2253: fix: intermittent PUT forward message delivery failure in NAT routing
## Problem

The `test_three_node_network_connectivity` test is flaky due to PUT forward messages being lost during NAT routing.

### Observed Behavior

1. Network connectivity is successfully established (all nodes see each other)
2. PUT operation starts with Peer1 sending `RequestPut` to Peer2 ✅
3. Peer2 receives `RequestPut` and sends `SeekNode` back ✅ 
4. Peer1 receives `SeekNode` and sends `PutForward` to Peer2 ❌
5. `PutForward` is logged as "Message successfully sent to peer connection via explicit address" **but never received**
6. Other messages (RequestSub, ProximityCache) sent 30ms later DO arrive ✅
7. Transaction times out

### Timeline from CI Logs

```
01:41:06.713 - Peer1 sends PutForward via explicit target address (NAT routing)
01:41:06.714 - "Message successfully sent to peer connection via explicit address"
01:41:06.747 - Peer1 sends RequestSub (different tx) - this DOES arrive
01:41:06.782 - Peer2 receives RequestSub and ProximityCache, but NOT PutForward
01:42:08.561 - Transaction timed out
```

### Root Cause Analysis

The issue is in the "explicit target address (NAT routing)" code path at `p2p_protoc.rs:612-657`. Messages are sent via `peer_connection.sender.send(Left(msg.clone())).await` which succeeds, but the message never reaches the receiver.

Key observations:
- The channel send succeeds (no error logged)
- Messages sent via different code path ("Sending outbound message to peer") DO arrive
- This is intermittent - sometimes the test passes on main

### Hypothesis

There may be a race condition or buffer issue in how messages are processed after being queued to the sender channel. The message gets successfully queued but then dropped or never processed.

### Affected Tests

- `test_three_node_network_connectivity` (connectivity.rs)
- `test_ping_blocked_peers*` (may have similar issue)

### Related Code

- `crates/core/src/node/network_bridge/p2p_protoc.rs:612-657` (NAT routing send path)
- `ConnectionEntry.sender: PeerConnChannelSender` (channel type)

### Impact

This is causing CI flakiness across multiple PRs (2246, 2251, 2252) and occasionally on main.

[AI-assisted - Claude]

### PR DESCRIPTION
**Pull request by sanity**
## Problem

The `test_three_node_network_connectivity` test was flaky due to PUT forward messages being lost during NAT routing. The issue manifested as:

1. Message successfully queued to channel via `peer_connection.sender.send()`
2. Log shows "Message successfully sent to peer connection via explicit address"
3. **But the message never arrives at the receiver**
4. Other messages sent milliseconds later DO arrive
5. Transaction times out

## Root Cause

The `peer_connection_listener` task uses `tokio::select!` to wait on:
- `rx.recv()` - outbound messages from the channel to send
- `conn.recv()` - inbound messages from the network

When a transport error occurs on `conn.recv()`:
1. The error branch is selected (randomly, since select is unbiased by default)
2. The task logs the error and immediately exits
3. The `rx` receiver is dropped
4. **Any pending outbound messages in the channel are lost**

This is a classic race condition where messages can be queued to the channel but never processed because the listener exits before draining them.

## Solution

Two changes to fix the race:

1. **Add `biased;` to the select!** - This ensures the outbound channel is checked first on each iteration, reducing the window where messages can be lost

2. **Add `drain_pending_messages()`** - Before terminating on transport errors, attempt to send any queued outbound messages. Even if the connection is degraded, some messages may still succeed.

## Testing

- Test passes consistently in local runs
- The fix is defensive - it attempts to process messages but gracefully handles failures during drain

## Impact

This should unblock PRs with red CI due to this flaky test (#2246, #2251, #2252).

Fixes #2253

[AI-assisted - Claude]

### CODE REVIEW

File: crates/core/src/node/network_bridge/p2p_protoc.rs [hunk 1]
```diff
@@ -2719,6 +2719,12 @@ async fn peer_connection_listener(
         }
 
         tokio::select! {
+            // Bias toward receiving from channel first to ensure outbound messages
+            // are sent before checking for inbound messages. This prevents a race
+            // where a transport error could cause us to exit before processing
+            // queued outbound messages.
+            biased;
```
Comment (iduartgomez) [inline crates/core/src/node/network_bridge/p2p_protoc.rs]: this just moves the problem elsewhere I think, instead we should drain all pending messages , this is a similar problem (or one of them), that triggered refactoring to PrioritySelect, a similar strategy should be aplied here.

**Comment by sanity** [comment]
Re-running CI to check for flakiness

File: crates/core/src/node/network_bridge/p2p_protoc.rs (hunk 1 above)
Comment (sanity) [reply crates/core/src/node/network_bridge/p2p_protoc.rs]: Good point - updated to use drain-then-select pattern instead of `biased`:

```rust
loop {
    // Drain all pending outbound messages first
    loop {
        match rx.try_recv() {
            Ok(msg) => { handle_outbound(msg).await; }
            Err(TryRecvError::Empty) => break,
            Err(TryRecvError::Disconnected) => return,
        }
    }
    // Now wait fairly for either channel
    tokio::select! {
        msg = rx.recv() => { ... }
        msg = conn.recv() => { ... }
    }
}
```

This ensures queued outbound messages are sent promptly without starving inbound.

[AI-assisted - Claude]

File: crates/core/src/contract/handler.rs [hunk 2]
```diff
@@ -273,12 +275,22 @@ impl ContractHandlerChannel<WaitingResolution> {
     pub async fn relay_transaction_result_to_client(
         &mut self,
     ) -> anyhow::Result<(ClientId, WaitingTransaction)> {
-        self.end
+        let rx = self
+            .end
             .wait_for_res_rx
-            .recv()
+            .as_mut()
+            .ok_or_else(|| anyhow::anyhow!("receiver already taken"))?;
```
Comment (iduartgomez) [inline crates/core/src/contract/handler.rs]: won't this just error out frequently if we are processing for multiple results in parallel? I am unconvinced this approach is not gonna result in trouble.

File: crates/core/src/contract/handler.rs [hunk 3]
```diff
@@ -273,12 +275,22 @@ impl ContractHandlerChannel<WaitingResolution> {
...
+        rx.recv()
             .await
             .ok_or_else(|| anyhow::anyhow!("channel dropped"))
     }
+
+    /// Take the underlying receiver for streaming. Returns None if already taken.
+    pub fn take_wait_for_res_receiver(
```
Comment (iduartgomez) [inline crates/core/src/contract/handler.rs]: why do we need to do this? are we doing this concurrently? would it may more sense moving from mpsc to a broadcast?

File: crates/core/src/node/network_bridge/p2p_protoc.rs [hunk 4]
```diff
@@ -2669,42 +2674,47 @@ async fn notify_transport_closed(
...
                         return;
                     }
-                    drained += 1;
-                    if drained >= MAX_IMMEDIATE_SENDS {
-                        break;
-                    }
                 }
-                Err(TryRecvError::Empty) => break,
-                Err(TryRecvError::Disconnected) => {
+                Err(tokio::sync::mpsc::error::TryRecvError::Empty) => break,
```
Comment (iduartgomez) [inline crates/core/src/node/network_bridge/p2p_protoc.rs]: can't we import at the top to reduce noise?

File: crates/core/src/node/network_bridge/priority_select.rs [hunk 5]
```diff
@@ -116,9 +96,19 @@ where
...
+    // to avoid recreating futures on each poll (fixes waker registration issue)
+    client_transaction_stream:
+        Option<tokio_stream::wrappers::ReceiverStream<(ClientId, WaitingTransaction)>>,
+
+    // Executor transaction stream - taken from the channel at construction time
+    // to avoid recreating futures on each poll (fixes waker registration issue)
+    executor_transaction_stream: Option<tokio_stream::wrappers::ReceiverStream<Transaction>>,
+
+    // Keep the original types for callback() and other methods that need them
+    #[allow(dead_code)]
```
Comment (iduartgomez) [inline crates/core/src/node/network_bridge/priority_select.rs]: why this is dead_code

File: crates/core/src/node/network_bridge/priority_select.rs [hunk 6]
```diff
@@ -116,9 +96,19 @@ where
...
     client_wait_for_transaction: C,
+    #[allow(dead_code)]
```
Comment (iduartgomez) [inline crates/core/src/node/network_bridge/priority_select.rs]: why this is dead_code now

File: crates/core/src/contract/handler.rs (hunk 2 above)
Comment (sanity) [reply crates/core/src/contract/handler.rs]: The receiver is taken once at startup when `PrioritySelectStream::new()` is constructed. After that, `relay_transaction_result_to_client()` is never called - the stream handles all receiving.

The error path exists as a safety check, but in practice the receiver is taken exactly once during initialization and stays taken for the node's lifetime.

[AI-assisted - Claude]

File: crates/core/src/contract/handler.rs (hunk 3 above)
Comment (sanity) [reply crates/core/src/contract/handler.rs]: The `take_receiver()` pattern is needed to convert the mpsc receiver into a `ReceiverStream` at construction time. This fixes the waker registration bug - streams maintain their wakers across polls, unlike futures recreated on each poll.

The receiver is taken once at startup and converted to a stream. It's not concurrent access - it's a one-time handoff from the channel to the stream wrapper.

Broadcast wouldn't help here - the issue was the polling pattern, not the channel type.

[AI-assisted - Claude]

File: crates/core/src/node/network_bridge/p2p_protoc.rs (hunk 4 above)
Comment (sanity) [reply crates/core/src/node/network_bridge/p2p_protoc.rs]: Done - moved `TryRecvError` to the import at the top of the file.

[AI-assisted - Claude]

File: crates/core/src/node/network_bridge/priority_select.rs (hunk 5 above)
Comment (sanity) [reply crates/core/src/node/network_bridge/priority_select.rs]: Removed - these fields were storing the original handlers after taking their receivers, but were never used. Now using `PhantomData<(C, E)>` to satisfy the type parameter requirements.

[AI-assisted - Claude]

File: crates/core/src/node/network_bridge/priority_select.rs (hunk 6 above)
Comment (sanity) [reply crates/core/src/node/network_bridge/priority_select.rs]: Same as above - removed. Both fields were only used to take their receivers during construction, then stored but never accessed again.

[AI-assisted - Claude]

File: crates/core/src/contract/handler.rs (hunk 3 above)
Comment (iduartgomez) [reply crates/core/src/contract/handler.rs]: I mean moving to broadcast so then we don't need to take, but if we are doing it once I guess is unnecessary.

File: crates/core/src/node/network_bridge/priority_select.rs [hunk 7]
```diff
@@ -41,49 +44,27 @@ pub(super) enum SelectResult {
...
-        Output = Result<
-            (
-                crate::client_events::ClientId,
-                crate::contract::WaitingTransaction,
-            ),
-            anyhow::Error,
-        >,
-    > + Send {
-        self.relay_transaction_result_to_client()
+    fn take_receiver(&mut self) -> Option<Receiver<(ClientId, WaitingTransaction)>> {
```
Comment (iduartgomez) [inline crates/core/src/node/network_bridge/priority_select.rs]: The whole idea of this type and its methods is to keep intent and understanding clear via types, shouldn't we implement stream (or sink if necessary) for the type instead of extracting streams and moving around by taking options? 

now is not clearn anymore when/where we are relay_transaction_result_to_client (which we still do somewhere!)

File: crates/core/src/node/network_bridge/priority_select.rs [hunk 8]
```diff
@@ -41,49 +44,27 @@ pub(super) enum SelectResult {
...
+        self.take_wait_for_res_receiver()
     }
 }
 
 impl ExecutorTransactionReceiver for ExecutorToEventLoopChannel<NetworkEventListenerHalve> {
-    fn transaction_from_executor(
-        &mut self,
-    ) -> impl Future<Output = anyhow::Result<Transaction>> + Send {
-        self.transaction_from_executor()
+    fn take_receiver(&mut self) -> Option<Receiver<Transaction>> {
```
Comment (iduartgomez) [inline crates/core/src/node/network_bridge/priority_select.rs]: similarly to the other comment,  by taking and handling a generic receiver now is not clear where we are calling this. Wouldn't it be better to implement stream for this type?

File: crates/core/src/node/network_bridge/priority_select.rs [hunk 9]
```diff
@@ -116,17 +97,26 @@ where
     // Generic to allow testing with mocks
     handshake_handler: H,
 
-    // These two are owned and we create futures from them that poll their internal state
-    // Generic to allow testing with mocks
-    client_wait_for_transaction: C,
-    executor_listener: E,
+    // Client transaction stream - taken from the handler at construction time
+    // to avoid recreating futures on each poll (fixes waker registration issue)
+    client_transaction_stream:
```
Comment (iduartgomez) [inline crates/core/src/node/network_bridge/priority_select.rs]: that we have to initialize with None here and insert some later is a bit of a code smell, pretty sure there is a better aproach (check the previous comments)

File: crates/core/src/node/network_bridge/priority_select.rs (hunk 8 above)
Comment (sanity) [reply crates/core/src/node/network_bridge/priority_select.rs]: ~~Same reasoning as above - implementing `Stream` for `ExecutorToEventLoopChannel` would be cleaner but requires more changes to the underlying type. The receiver extraction is a minimal fix.~~

**Update:** Now implemented `Stream` directly on `ExecutorToEventLoopChannel<NetworkEventListenerHalve>` per Nacho's feedback. The receiver extraction pattern has been removed.

File: crates/core/src/node/network_bridge/priority_select.rs (hunk 9 above)
Comment (sanity) [reply crates/core/src/node/network_bridge/priority_select.rs]: The `Option<ReceiverStream<...>>` is needed because `take_receiver()` returns `Option` - some implementations might not have a receiver (e.g., in tests with mock types).

The pattern is: take receiver at construction, wrap in stream, store as `Option`. The `None` case only happens if the receiver was already taken or doesn't exist.

Agreed this is a code smell - implementing `Stream` directly on the handler types (as suggested in your other comments) would be cleaner.

[AI-assisted - Claude]

File: crates/core/src/node/network_bridge/priority_select.rs (hunk 7 above)
Comment (sanity) [reply crates/core/src/node/network_bridge/priority_select.rs]: Done - implemented `Stream` directly on `ContractHandlerChannel<WaitingResolution>` and `ExecutorToEventLoopChannel<NetworkEventListenerHalve>` instead of extracting receivers.

The `PrioritySelectStream` now stores these handler types directly and polls them as streams, which is cleaner than the previous approach with traits and `take_receiver()` methods. Also removed the `PhantomData` since the type parameters are now used directly.

[AI-assisted - Claude]

File: crates/core/src/contract/executor.rs [hunk 10]
```diff
@@ -383,7 +399,7 @@ pub(crate) struct Callback {
 pub(crate) struct NetworkEventListenerHalve {
     /// this is the receiver end of the Executor halve, which will be sent from the executor
     /// when a callback is expected for a given transaction
-    waiting_for_op_rx: mpsc::Receiver<Transaction>,
+    waiting_for_op_rx: Option<mpsc::Receiver<Transaction>>,
```
Comment (iduartgomez) [inline crates/core/src/contract/executor.rs]: Does this need to be an option now?
