### PR TITLE
fix: reset THREAD_INDEX in set_seed() for parallel test determinism

### LINKED ISSUE #3078: fix: ping integration tests fail ~100% in CI due to 30s gateway backoff
## Problem

The `freenet-ping-app` integration tests fail with ~100% aggregate rate in CI. In PR #3077 alone, **5 consecutive CI runs** each failed on a **different** ping test, all with `"Node1 failed to get 1 ring connection(s) within 120s"`:

1. `test_ping_blocked_peers`
2. `test_ping_multi_node`
3. `test_ping_blocked_peers_solution`
4. `test_ping_partially_connected_network`
5. `test_ping_application_loop`

This blocks all PR merges and wastes ~18 minutes per CI re-trigger.

## Root Cause: Backoff Death Spiral

The `PeerConnectionBackoff` in `crates/core/src/ring/peer_connection_backoff.rs` has a **30-second** base interval with exponential growth:

```
30s → 60s → 120s → 240s → 480s → 600s (cap)
```

Under CI resource pressure:
1. First connect attempt from joiner to gateway times out
2. `handle_aborted_op` records the failure and enters **30s backoff**
3. If the retry also fails → **60s backoff**
4. Two failures = 90+ seconds of cumulative waiting with a 120s test timeout → test fails

### Compounding factor: Event loop blocking

The backoff sleep in `node/mod.rs:1611` is awaited **inline** within the `select!` event loop. While sleeping, the node cannot process incoming handshakes, respond to diagnostic queries, or handle any network events — making recovery harder.

## Proposed Fix

1. **Make gateway backoff configurable** with shorter defaults for test environments (2-5s base instead of 30s). Use `NodeConfig` or an environment variable.
2. **Don't block the event loop** during backoff — spawn the retry as a separate task instead of awaiting inline.
3. **Use `connect_ws_with_retry`** consistently in `run_app_blocked_peers.rs` tests (currently uses raw `connect_async_with_config` after a fixed 25s sleep).

## Related

- Supersedes #3036 (same symptom, this issue identifies the root cause)
- Blocking PR #3077 and other PRs

[AI-assisted - Claude]

### PR DESCRIPTION
**Pull request by sanity**
## Problem

Three independent sources of test flakiness in CI:

### 1. THREAD_INDEX race in parallel test execution

Simulation tests were flaky because `GlobalRng::thread_index()` — used to perturb RNG seeds and compute ID counter offsets — varied depending on which OS thread ran each test. The old mitigation (`reset_thread_index_counter()`) reset a **global** `AtomicU64`, which is racy when multiple tests run in parallel.

### 2. Gateway backoff too aggressive for CI

The `PeerConnectionBackoff` uses a 30-second base interval (production-appropriate), but in CI where tests run on localhost under resource pressure, a single failed connect attempt triggers a 30-second backoff that consumes most of the test timeout.

### 3. Ping test connection timeout too tight

The `wait_for_node_connected` timeout of 120s is insufficient under CI resource pressure, especially for tests that run later in their binary when the machine is loaded. This caused `test_ping_blocked_peers_solution` and `test_ping_partially_connected_network` to fail ~50% of the time.

### THREAD_INDEX fix

`set_seed()` now resets the **thread-local** `THREAD_INDEX` to `Some(0)`, ensuring every seeded thread behaves identically to thread 0 regardless of its actual OS thread assignment. The old racy `reset_thread_index_counter()` function and all callers are removed.

### CI backoff fix

Added `FREENET_BACKOFF_BASE_SECS` environment variable support to `PeerConnectionBackoff::new()`, set to 5s in CI (down from default 30s). This gives tests enough retry budget within their timeouts.

### Ping test timeout fix

Increased `wait_for_node_connected` timeout from 120s to 180s in the blocked_peers and partially_connected_network tests. This gives 50% more headroom under CI resource pressure without extending the overall test budget (outer timeout is 300s).

## Testing

- **10/10 consecutive parallel runs pass** (380 test executions, zero failures)
- Previously: main had ~20% failure rate per run in parallel execution
- Unit test added for `set_seed()` THREAD_INDEX pinning contract

## Related

Related: #3067 — the specific convergence failure was caused by the missing notification_channel (fixed in #3072), but the thread index race made diagnosis harder.
Fixes #3078, #3036

[AI-assisted - Claude]

### CODE REVIEW

File: crates/core/src/ring/peer_connection_backoff.rs [hunk 1]
```diff
@@ -47,9 +47,16 @@ impl PeerConnectionBackoff {
     const DEFAULT_MAX_ENTRIES: usize = 1024;
 
     /// Create a new backoff tracker with default settings.
+    ///
+    /// Respects `FREENET_BACKOFF_BASE_SECS` environment variable to override the
+    /// base interval (useful for CI/integration tests where 30s is too aggressive).
     pub fn new() -> Self {
-        let config =
-            ExponentialBackoff::new(Self::DEFAULT_BASE_INTERVAL, Self::DEFAULT_MAX_BACKOFF);
+        let base = std::env::var("FREENET_BACKOFF_BASE_SECS")
```
Comment (iduartgomez) [inline crates/core/src/ring/peer_connection_backoff.rs:54]: this should go into config
